# Generated by Django 3.0.5 on 2020-10-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Name',
            field=models.TextField(max_length=500),
        ),
    ]
